name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3
    - name: Install GTK4
      run: |
        sudo apt-get update
        sudo apt-get install libglib2.0
        sudo apt-get install libgtk-4-1
        sudo apt-get install libpango1.0
        sudo apt-get install libgdk-pixbuf-2.0
        sudo apt-get install libgtk-4-dev
        sudo apt-get install libadwaita-1-0
        sudo apt-get install libadwaita-1-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
