name: Rust (Windows)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-gtk4
          mingw-w64-x86_64-libadwaita
          mingw-w64-x86_64-gettext
          mingw-w64-x86_64-glib2
          mingw-w64-x86_64-pkg-config
          
    - name: Add MSYS2 to PATH
      shell: bash
      run: echo "C:/msys64/mingw64/bin" >> $GITHUB_PATH

    - name: Set PKG_CONFIG_PATH
      run: echo "PKG_CONFIG_PATH=C:/msys64/mingw64/lib/pkgconfig" >> $GITHUB_ENV
    
    - name: Check for pkg-config
      shell: bash
      run: |
        which pkg-config || echo "pkg-config not found"
        /c/msys64/mingw64/bin/pkg-config --version || echo "pkg-config not working"
        echo $PATH        
    
    - name: Build
      shell: bash
      run: cargo build --verbose

    - name: Run tests
      shell: bash
      run: cargo test --verbose
